### ISSUE TITLE
Save wont save the file

### ISSUE THREAD

**Issue by MrAmericanMike** [piyushsarkar/vscode-css-property-sorter#5]
First of all, thanks for implementing my previous suggestion and supporting files like Svelte.

One thing I have noticed since this update, when I have for example:

```json
"editor.formatOnSave": true,
"sortcss.sortOnSave": true,
```

When I save a file, it performs the sorting, but the file itself isn't saved, so I have to do Save twice.

PS: On a sidenote, and not to open a different issue (Let me know if you want me to report this separately.

Lets say I have:

```css
	.app-grid {
		grid-template-rows: repeat(5, minmax(0, 1fr));
		grid-template-columns: repeat(4, minmax(0, 1fr));
		display: grid;
		justify-content: space-between;
		align-items: flex-start;
		background-color: red;
		padding: 1rem 1rem 0 1rem;
		width: 100%;
	}
```

And my cursor is at the end of `display: grid;` After sorting the resulting sorted css rules looks like:

```css
	.app-grid {
		display: grid;
		grid-template-rows: repeat(5, minmax(0, 1fr));
		grid-template-columns: repeat(4, minmax(0, 1fr));
		justify-content: space-between;
		align-items: flex-start;
		background-color: red;
		padding: 1rem 1rem 0 1rem;
		width: 100%;
	}
```

But my cursor ends at the end of `grid-template-columns: repeat(4, minmax(0, 1fr));`

Would it be possible to track where the cursor is before sorting and move it if the line we were on moved?

**Comment by piyushsarkar** [comment]
@MrAmericanMike, Thanks for reporting the issue. I'll look into this.

**Comment by piyushsarkar** [comment]
@MrAmericanMike, The "sort on save" bug has been fixed in https://github.com/piyushsarkar/vscode-css-property-sorter/pull/6. 
Please update the extension to the latest version to get the fix.

**And Regarding the cursor position issue:** 
It is possible to track and restore the cursor position, but doing so could introduce edge cases, performance issues, or bugs, especially when combined with other formatters or extensions during save. It's not at the top of my list right now, but I'll revisit this feature when I have the chance.

**Comment by MrAmericanMike** [comment]
Thanks a lot. 

I am on 0.1.0 looks like saving is working fine on some of my project, but not in others. I'll try to track what the differences are and what could be causing this inconsistency. Hopefully I can do some tests during the week and post back.

**Comment by MrAmericanMike** [comment]
One thing I just noticed (And maybe the cause of inconsistency) I just noticed this, for example on this CSS block:


```css
	.scrollable {
		display: flex;
		background: url("/background.jpg");
		background-position: center;
		background-size: cover;
		width: 100vw;
		height: 100vh;
		-ms-overflow-style: none;
		overflow: scroll;
		scroll-snap-type: x mandatory;
		scrollbar-width: none;
		color: white;
		font-size: 0.875rem;
		line-height: 1.25rem;
	}
```

The rule `-ms-overflow-style: none;` causes issues. When present, the sorter will sort everything above it as 1 block, and everything below is as another block. 

PS: Not sure if this is related with the inconsistency with the save issue, but one thing I noticed.

I believe the issue is caused by some weird combination when Svelte for VS Code is running (Which is needed so Sort CSS knows to treat the <style> as css and sort on save).
But it's inconsistent, if I disable and then enable it, then it will sort and save without any problem. But if I restart VSCode then the issue comes back. But then I open a different project, with the same profile, that also has Svelte for VS Code and everything works fine.
I will close, as now as I keep testing it looks like it's working fine in both projects once again. I wonder if VSCode is doing something dumb or something.
If at some point I notice a clear cause will let you know.
